addons:
  sauce_connect:
    username: "dreamrulez07"
    access_key: "fb789f94-e013-4026-8cd9-27f0285e0147"

before_install:
  - git submodule update --init --recursive

language: ruby

rvm:
  - 1.9.3

env:
  - DB=mysql

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - RAILS_ENV=test bundle exec rake --trace webdriver browser=firefox
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database privly_test'
