before_install:
  - git submodule update --init --recursive

language: ruby

rvm:
  - 1.9.3

env:
  - DB=mysql

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - RAILS_ENV=test bundle exec rake --trace phantomjs
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database privly_test'
